name: Build EXE

on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build EXE
        run: npx electron-packager . MandinePOS --platform=win32 --arch=x64

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: MandinePOS
          path: MandinePOS-win32-x64
